---
- name: Ensure ByzRP directory
  file:
    path: /opt/byzrp/
    state: directory

- name: Copy peer list to nodes
  copy:
    src: prep/peers.lst
    dest: /opt/byzrp/peers.lst

- name: Copy root certificate to nodes
  copy:
    src: "prep/root.crt"
    dest: /opt/byzrp/root.crt

- name: Copy keys to nodes
  copy:
    src: "prep/{{ ansible_host }}.key"
    dest: /opt/byzrp/server.key

- name: Copy certificates to nodes
  copy:
    src: "prep/{{ ansible_host }}.crt"
    dest: /opt/byzrp/server.crt

- name: Copy Docker image to nodes
  copy:
    src: prep/byzrp.img
    dest: /opt/byzrp/byzrp.img

- name: Load docker image
  command: docker load -i /opt/byzrp/byzrp.img

- name: Run Docker container
  docker_container:
    name: byzrp
    image: byzrp
    state: started
    restart_policy: unless-stopped
    ports:
      - "443:443"
      - "8282:8282"
    volumes:
      - /opt/byzrp/server.crt:/etc/ssl/certs/server.crt
      - /opt/byzrp/server.key:/etc/ssl/private/server.key
      - /opt/byzrp/root.crt:/etc/ssl/certs/root.crt
      - /opt/byzrp/peers.lst:/data/out/share/peers.lst
    env:
      SELF_IP: "{{ ansible_host }}"
    detach: true
