---
all:
  hosts:
    byzrp1:
      ansible_host: 192.168.56.34
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/byzrp1/virtualbox/private_key
    byzrp2:
      ansible_host: 192.168.56.35
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/byzrp2/virtualbox/private_key
    byzrp3:
      ansible_host: 192.168.56.36
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/byzrp3/virtualbox/private_key

  children:
    mon:
      hosts:
        byzrp1:
